### ISSUE TITLE
Making fs.createReadStream work in 0.8 and 0.10

### ISSUE THREAD

**Issue by wibblymat** [nodejs/readable-stream#69]
I have some code that works in 0.10. I create a stream with fs.createReadStream and then assign handlers for 'readable', 'end' and 'error' events.

I was under the impression that `readable-stream` would let me make my code be backwards compatible with 0.8, but I am unsure how I use it.

Here is a small example

``` javascript
var fs = require('fs');

var stream = fs.createReadStream('test.txt');

stream.on('readable', function () {
    console.log('The stream became readable');

    var chunk = stream.read(10);

    while (chunk !== null) {
        console.log('Read the next 10 bytes of the file. They are "' + chunk.toString() + '"');
        chunk = stream.read(10);
    }
});

stream.on('error', function () {
    console.log('There was an error');
});

stream.on('end', function () {
    console.log('The stream ended');
});
```

This code works in 0.10 but not 0.8, as expected. If I replace

``` javascript
var fs = require('fs');
```

with

``` javascript
var fs = require('readable-stream/fs');
```

I get the same error in both 0.8 and 0.10:

```
/my/project/path/node_modules/readable-stream/fs.js:1510
    cb(null, b);
    ^
TypeError: undefined is not a function
    at onread (/my/project/path/node_modules/readable-stream/fs.js:1510:5)
    at Object.wrapper [as oncomplete] (/my/project/path/node_modules/readable-stream/fs.js:420:17)
```

Is there any documentation that explains what I should be doing here?
